### ISSUE TITLE
read_ts not working for much longer

### ISSUE THREAD

**Issue by dude233** [KOF-ch/tstools#296]
read_ts() will not work much longer, melt() needs namespace reshape2

Warning message:
In melt(data, id.vars = "date", variable.name = "series") :
The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(data). In the next version, this warning will become an error.

**Comment by Kjir** [comment]
A new version was released with a fix for this issue

**Comment by Kjir** [comment]
Version 0.4.2
